barang/urls.py
from django.urls import path
from .views import barang_view, semua_barang_view, barang_view_buy, barang_view_review

app_name = 'barang'

urlpatterns = [
    path('<int:id>/buy', barang_view_buy, name='barang-buy'),
    path('<int:id>/review', barang_view_review, name='barang-review'),
    path('<int:id>', barang_view, name='barang-detail'),
    path('all/<str:filter>', semua_barang_view, name='barang-filter'),
    path('all', semua_barang_view, name='barang-all')
]

kategori/urls.py
from django.urls import path
from .views import kategori_view

app_name = 'kategori'

urlpatterns = [
    path('<str:kategori>', kategori_view, name='kategori'),
    path('', kategori_view, name='kategori-default')
]

kupon/urls.py
from django.urls import path
from .views import semua_kupon_view

app_name = 'kupon'

urlpatterns = [
    path('', semua_kupon_view, name='semua-kupon')
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('barang/', include('barang.urls')),
    path('kategori/', include('kategori.urls')),
    path('kupon/', include('kupon.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('shopadmin/', include('shopadmin.urls')),
    path('', include('landing.urls'))
]

kategori/models.py
from django.db import models


class Kategori(models.Model):
    nama = models.CharField(max_length=70, primary_key=True)

kategori/views.py
from django.shortcuts import render
from .models import Kategori
from barang.models import Barang


def kategori_view(request, kategori=""):
    kategori_all = Kategori.objects.all()
    try:
        kategori_requested = kategori_all.get(nama=kategori)
    except:
        kategori_requested = kategori_all[0]
    barang_requested = Barang.objects.filter(kategori=kategori_requested)
    context = {
        "categories": kategori_all,
        "prod": barang_requested,
        "cat": kategori_requested
    }
    return render(request, "kategori/kategori.html", context)

kategori/templates/kategori/kategori.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="container">
  <h2 class="text-center">
    Kategori {{cat.nama}}
  </h2>
  <div class="row mt-3">
    {% for product in prod %}
    <div class="col-sm-3">
      <a href="{% url 'barang:barang-detail' id=product.id %}">
        <div class="online-card text-center all-product-card mb-4">
          <img src="{{product.gambar}}" class="all-product-image" />
          <div class="item-description w-100 px-3">
            <span class="text-muted">{{product.stok}} pcs</span>
            <h4>{{product.nama}}</h4>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{% load static %} {% endblock %} {% block head %}
<title>{{cat.nama }} | Tk.PePeW Online Shop</title>
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css" />
<link rel="stylesheet" href="{% static 'onlineshop/styles.css' %}" />

{% endblock %} {% block leftsidecontent %}
<div class="d-flex flex-column align-items-center" id="side-category">
  <h3 class="font-weight-bold categ-title">CATEGORIES</h3>
  <div class="category">
    <ul class="nav flex-column">
      {% for cat in categories %}
      <li class="nav-item">
        <a
          class="nav-link category-link"
          href="{% url 'kategori:kategori' kategori=cat.nama %}"
        >
          <img
            src="{% static 'onlineshop/star.svg'%}"
            class="icon-star"
          />{{cat.nama}}</a
        >
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %} {% block rightsidecontent %}
<div>{% include 'includes/recommended.html' %}</div>
{% endblock %}