kupon/urls.py
from django.urls import path
from .views import semua_kupon_view

app_name = 'kupon'

urlpatterns = [
    path('', semua_kupon_view, name='semua-kupon')
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('barang/', include('barang.urls')),
    path('kategori/', include('kategori.urls')),
    path('kupon/', include('kupon.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('shopadmin/', include('shopadmin.urls')),
    path('', include('landing.urls'))
]

shopadmin/urls.py
from django.urls import path
from .views import admin_view, add_view

app_name = 'shopadmin'

urlpatterns = [
    path('', admin_view, name='shop-admin'),
    path('add/<str:name>', add_view, name='add')
]

shopadmin/models.py
from django.db import models

# Create your models here.

shopadmin/forms.py
from django import forms

from barang.models import Barang
from kupon.models import Kupon
from kategori.models import Kategori


class BarangCreateForm(forms.ModelForm):
    class Meta:
        model = Barang
        fields = "__all__"


class KuponCreateForm(forms.ModelForm):
    expired = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.TextInput(
            attrs={'type': 'datetime-local'}
        )
    )

    class Meta:
        model = Kupon
        fields = "__all__"


class KategoriCreateForm(forms.ModelForm):
    class Meta:
        model = Kategori
        fields = "__all__"

shopadmin/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import KategoriCreateForm, BarangCreateForm, KuponCreateForm


@login_required
def admin_view(request):
    return render(request, "shopadmin/admin.html")


def handle_post_add(request, name):
    if name.lower() == "kupon":
        form = KuponCreateForm(request.POST)
        name = "Kupon"
    elif name.lower() == "kategori":
        form = KategoriCreateForm(request.POST)
        name = "Kategori"
    elif name.lower() == "barang":
        form = BarangCreateForm(request.POST)
        name = "Barang"
    if form.is_valid():
        form.save()
        return redirect("kupon:semua-kupon")
    context = {
        "form": form,
        "name": name
    }
    return render(request, "shopadmin/add.html", context)


@login_required
def add_view(request, name):
    if request.method == "POST":
        return handle_post_add(request, name)
    if name == "kupon":
        kupon_form = KuponCreateForm()
        context = {
            "form": kupon_form,
            "name": "Kupon"
        }
    elif name == "kategori":
        kategori_form = KategoriCreateForm()
        context = {
            "form": kategori_form,
            "name": "Kategori"
        }
    elif name == "barang":
        barang_form = BarangCreateForm()
        context = {
            "form": barang_form,
            "name": "Barang"

        }
    else:
        return render(request, "shopadmin/admin.html")
    return render(request, "shopadmin/add.html", context)

shopadmin/templates/shopadmin/add.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="container">
  <div class="container w-50 d-flex flex-column">
    <div class="mt-4 mb-5 card text-center">
      <div class="card-body">
        <h2>Add {{name}}</h2>
        <form action="{% url 'shopadmin:add' name %}" method="POST">
          {% csrf_token %} {% load crispy_forms_tags %} {{form|crispy}}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block head %}
<title>
  Admin | Tk.PePeW Online Shop
</title>

{% endblock %} {% block rightsidecontent %} {% include 'includes/recommended.html' %} {% endblock %}

shopadmin/templates/shopadmin/admin.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="container">
  <h2 class="text-center">
    Admin
  </h2>
  <div class="container w-50 d-flex flex-column">
    <div id="sidebar" class="mx-5 mt-4 px-4 py-2">
      <ul class="nav flex-column text-center">
        <li class="nav-item">
          <a href="{% url 'shopadmin:add' 'barang' %}" class="nav-link sidelink"
            >Add Product</a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url 'shopadmin:add' 'kategori' %}"
            class="nav-link sidelink"
            >Add Category</a
          >
        </li>
        <li class="nav-item">
          <a href="{% url 'shopadmin:add' 'kupon' %}" class="nav-link sidelink"
            >Add Coupon</a
          >
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %} {% block head %}
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css" />
<title>
  Admin | Tk.PePeW Online Shop
</title>

{% endblock %} {% block rightsidecontent %} {% include 'includes/recommended.html' %} {% endblock %}